### ISSUE TITLE
[Bug]: `v5` - using tags for individual stories causes error

### ISSUE THREAD

**Issue by bhvngt** [storybookjs/addon-svelte-csf#200]
### Describe the bug

When `v5` of this addon is used, using tags for individual stories causes crash.

### Steps to reproduce the behavior

Here's the [reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-bxesk4) of this issue.

Note: For some unknown reason, stackblitz does not save .storybook folder. Hence, `storybook init` will have to be run to render storybook

Make following changes to `src/stories/Button.stories.svelte` file

```
<Story name="Secondary" tags={["!dev"]}/>
```

### Expected behavior

Expecting `Secondary` story to disappear from storybook sidebar.

### Screenshots and/or logs

![image](https://github.com/user-attachments/assets/e6e75ae1-c938-4a80-98c9-b0c8989da227)

**Comment by xeho91** [comment]
Hey @bhvngt, thank you for testing out `v5` ❤️ and spotting this bug!
I confirm I was able to reproduce the issue.

@JReinhold You could extract more info from the console in web browser dev tools.

I handpicked this one:

```txt
runtime.js:4708 SB_PREVIEW_API_0006 (StoryIndexFetchError): Error fetching `/index.json`:

TypeError: Cannot read properties of undefined (reading 'type')

If you are in development, this likely indicates a problem with your Storybook process,
check the terminal for errors.

If you are in a deployed Storybook, there may have been an issue deploying the full Storybook
build.
    at ts.getStoryIndexFromServer (https://sveltejskittemplatedefaultbxes-hfev--6006--60a75bde.local-credentialless.webcontainer.io/sb-preview/runtime.js:8449:11)
    at async ts.initializeWithProjectAnnotations (https://sveltejskittemplatedefaultbxes-hfev--6006--60a75bde.local-credentialless.webcontainer.io/sb-preview/runtime.js:8432:15)
    at async ts.initialize (https://sveltejskittemplatedefaultbxes-hfev--6006--60a75bde.local-credentialless.webcontainer.io/sb-preview/runtime.js:8406:39)
```

Is it possible that it could be an upstream issue in `@storybook/preview-api`?

**Comment by JReinhold** [comment]
I'm looking into this.

**Comment by bhvngt** [comment]
Thanks @JReinhold
