### ISSUE TITLE
[Bug] Custom errors thrown during build are being swallowed by Vite

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/addon-svelte-csf#221]
# FALSE, SEE COMMENT BELOW

### Describe the bug

The following stories file has two stories with the same name _"Default"_. It should throw a nice error here because this is not valid. But it doesn't. `dev` just ignores it, and `build` crashes with a hard to parse Vite error.

```svelte
<script lang="ts" context="module">
    import { defineMeta } from '@storybook/addon-svelte-csf';

    const { Story } = defineMeta({
        title: 'Cart/VoucherForm',
        component: VoucherForm,
    });
</script>

<script lang="ts">
    import VoucherForm from '@components/Cart/VoucherForm.svelte';
    import { expect, within } from '@storybook/test';
    import type { ComponentProps } from 'svelte';

    import { allModes } from '$storybook/modes';
</script>

{#snippet template(args: ComponentProps<VoucherForm>)}
    <VoucherForm {...args} />
{/snippet}

<Story
    name="Default"
    children={template}
/>

<Story
    name="Default"
    children={template}
/>
```

**Comment by JReinhold** [comment]
In `dev` I get the proper error __when visiting the story__ (so you might miss this):

```
21:43:29 [vite] Internal server error: Duplicate exportNames found between two '<Story />' definitions in stories file: file:///Users/jeppe/dev/temp/svelte-csf-conflicts/src/stories/Button.stories.svelte

First instance: <Story name="Primary" exportName="Primary" ... />
Second instance: <Story name="Primary" exportName="Primary" ... />

This can happen when 'exportName' is implicitly derived by 'name'.
Complex names will be simplified to a PascalCased, valid JavaScript variable name,
eg. 'Some story name!!' will be converted to 'SomeStoryName'.
You can fix this collision by providing a unique 'exportName' prop with <Story exportName="SomeUniqueExportName" ... />.

More info: https://github.com/storybookjs/addon-svelte-csf/blob/v5.0.0-next.7/ERRORS.md#SB_SVELTE_CSF_PARSER_ANALYSE_STORY_0006

  Plugin: storybook:addon-svelte-csf-plugin-post
  File: /Users/jeppe/dev/temp/svelte-csf-conflicts/src/stories/Button.stories.svelte
```

In `build` I get a bad error:

```
=> Failed to build the preview
TypeError: Cannot set property message of  which has only a getter
    at enhanceRollupError (file://./node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65318:15)
    at build (file://./node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65456:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async build (./node_modules/@storybook/builder-vite/dist/index.js:58:230)
    at async Promise.all (index 0)
    at async Module.build2 (./node_modules/@storybook/builder-vite/dist/index.js:58:5160)
    at async Promise.all (index 0)
    at async buildStaticStandalone (./node_modules/@storybook/core/dist/core-server/index.cjs:46960:3)
    at async withTelemetry (./node_modules/@storybook/core/dist/core-server/index.cjs:47080:12)
    at async build (./node_modules/@storybook/core/dist/cli/bin/index.cjs:2841:3)
```
