### ISSUE TITLE
[Bug] Fails to load in Node 23 with `SB_CORE-SERVER_0002 (CriticalPresetLoadError)`

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/addon-svelte-csf#229]
> [!NOTE]
> This issue has a [temporary workaround](https://github.com/storybookjs/addon-svelte-csf/issues/229#issuecomment-2540390494)

### Describe the bug

When starting up a fresh Storybook project (both 8.3 and 8.4) with Svelte 5 and v5 of this addon, it fails to start with the error pasted below.

Downgrading Node to v22 fixes it. So does removing the addon and removing `.svelte` from the `stories` glob, which is why I've narrowed it down to this.

### Screenshots and/or logs

```
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./node_modules/@storybook/addon-svelte-csf/dist/preset.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import './node_modules/@storybook/addon-svelte-csf/dist/compiler/post-transform/story' is not supported resolving ES modules imported from ./node_modules/@storybook/addon-svelte-csf/dist/compiler/post-transform/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:349:53)
    at new ModuleJobSync (node:internal/modules/esm/module_job:338:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:409:11)
    at new ModuleJobSync (node:internal/modules/esm/module_job:338:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:409:11)

More info:

    at loadPreset (./node_modules/@storybook/core/dist/common/index.cjs:139445:13)

More info:

    at loadPreset (./node_modules/@storybook/core/dist/common/index.cjs:139445:13)
    at async Promise.all (index 1)
    at async loadPresets (./node_modules/@storybook/core/dist/common/index.cjs:139455:55)
    at async getPresets (./node_modules/@storybook/core/dist/common/index.cjs:139488:11)
    at async buildDevStandalone (./node_modules/@storybook/core/dist/core-server/index.cjs:48473:11)
    at async withTelemetry (./node_modules/@storybook/core/dist/core-server/index.cjs:47080:12)
    at async dev (./node_modules/@storybook/core/dist/cli/bin/index.cjs:2877:3)
    at async r.<anonymous> (./node_modules/@storybook/core/dist/cli/bin/index.cjs:2929:74)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

WARN   Failed to load preset: {"type":"presets","name":"/Users/jeppe/dev/temp/sv2/node_modules/@storybook/addon-svelte-csf/dist/preset.js"} on level 1
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import './node_modules/@storybook/addon-svelte-csf/dist/compiler/post-transform/story' is not supported resolving ES modules imported from ./node_modules/@storybook/addon-svelte-csf/dist/compiler/post-transform/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:349:53)
    at new ModuleJobSync (node:internal/modules/esm/module_job:338:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:409:11)
    at new ModuleJobSync (node:internal/modules/esm/module_job:338:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:409:11)
(node:51681) ExperimentalWarning: CommonJS module /Users/jeppe/dev/temp/sv2/node_modules/@storybook/core/dist/common/index.cjs is loading ES Module /Users/jeppe/dev/temp/sv2/node_modules/@storybook/addon-svelte-csf/dist/preset.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51681) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

### Environment

```
Storybook Environment Info:

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    **Node: 23.1.0** - ~/Library/Caches/fnm_multishells/45040_1731443426590/bin/node
    npm: 10.9.0 - ~/Library/Caches/fnm_multishells/45040_1731443426590/bin/npm <----- active
    pnpm: 9.12.0 - ~/Library/Caches/fnm_multishells/45040_1731443426590/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Edge: 130.0.2849.80
    Safari: 16.2
  npmPackages:
    @storybook/addon-essentials: 8.3.6 => 8.3.6
    @storybook/addon-interactions: 8.3.6 => 8.3.6
    @storybook/addon-links: 8.3.6 => 8.3.6
    @storybook/addon-svelte-csf: ^5.0.0-next.11 => 5.0.0-next.11
    @storybook/blocks: 8.3.6 => 8.3.6
    @storybook/svelte: 8.3.6 => 8.3.6
    @storybook/sveltekit: 8.3.6 => 8.3.6
    @storybook/test: 8.3.6 => 8.3.6
    storybook: 8.3.6 => 8.3.6
```

## Additional Context

Originally reported in https://github.com/sveltejs/cli/issues/296#issuecomment-2471519367 and https://github.com/sveltejs/cli/issues/295

**Comment by xeho91** [comment]
Hm, so from the initial investigation.

I've been manually fixing the `[ERR_UNSUPPORTED_DIR_IMPORT]` errors inside `node_modules/`. Then I ended up different errors. The last one that blocked me from continuing is:

```txt
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/xeho91/Nextcloud/Projects/xeho91/xeho91/node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.11_@storybook+svelte@8.4.2_storybook@8.4.2_prettier@3._uocwypg2nwmmz5omf6wak5chkq/node_modules/@storybook/node-logger/package.json imported from /Users/xeho91/Nextcloud/Projects/xeho91/xeho91/node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.11_@storybook+svelte@8.4.2_storybook@8.4.2_prettier@3._uocwypg2nwmmz5omf6wak5chkq/node_modules/@storybook/addon-svelte-csf/dist/compiler/post-transform/story/insert-description.js
```

While everything seems to be OK inside the `package.json` exports inside `@storybook/node-logger`. 🤷 

There either has been some breaking change in Node.js that I am not aware of, or something else is causing all this Jenga tower to fail with different errors.

**Comment by dominikg** [comment]
fyi i got an `[ERR_UNSUPPORTED_DIR_IMPORT]` error running storybook + svelte 5 with node 22.12.0 that went away after downgrading to 20.18

**Comment by JReinhold** [comment]
I'm concluding two things here (and based on some other work I'm doing currently to fix #213)

1. We need to get rid of the `#` import maps, Node just behaves funky when it sees them in `node_modules`, sometimes it respects them, sometimes it ignores them. I think perhaps the feature is only really meant for applications and not libraries, but I haven't found documentation anywhere backing that hunch up.
2. We need to replace implicit `index.js` imports with explicit ones, which this `ERR_UNSUPPORTED_DIR_IMPORT` directly points at. So eg. here: https://github.com/storybookjs/addon-svelte-csf/blob/52910d0c280554e189d5788a6d379249e9ef38b2/src/compiler/post-transform/index.ts#L3
we need to change that:

```diff
- import { transformStory } from './story';
+ import { transformStory } from './story/index.js';
```

I just noticed that is also mentioned in the Svelte docs: https://svelte.dev/docs/kit/packaging#Caveats

We are slightly inconvenienced by the fact that `@sveltejs/package` does very little bundling and just wraps `tsc`, but setting `tsup` or similar up with Svelte and types is non-trivial unfortunately.

**Comment by xeho91** [comment]
Aye, I'm in favor of removing the `package.json#imports`.

Given this experience, I agree with your conclusion:
> **I think perhaps the feature is only really meant for applications and not libraries**

**Comment by JReinhold** [comment]
Note, to truly work with Node 23, we need this released too: https://github.com/storybookjs/storybook/pull/30093

**Comment by ryu-man** [comment]
I got similar issue when deploying a monorepo project to Vercel; although the build works fine locally, you can checkout the following log from vercel build log

```
[14:55:37.073] Running build in Washington, D.C., USA (East) – iad1
[14:55:37.951] Cloning github.com/ryu-man/svelte-fui (Branch: ryuman/svelte-5-migration, Commit: 60aa8a2)
[14:55:38.289] Cloning completed: 337.916ms
[14:55:41.953] Restored build cache from previous deployment (BydE3KdQ8DpbDPtpKoxceCET7cNJ)
[14:55:42.046] Running "vercel build"
[14:55:42.521] Vercel CLI 39.2.0
[14:55:44.830] Warning: Detected "engines": { "node": ">=20.x" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[14:55:44.865] Detected `pnpm-lock.yaml` version 6 generated by pnpm@8.x
[14:55:44.866] Running "install" command: `pnpm install --ignore-scripts`...
[14:55:45.743] Scope: all 5 workspace projects
[14:55:45.908] Lockfile is up to date, resolution step is skipped
[14:55:47.316] Progress: resolved 0, reused 0, downloaded 1, added 0
[14:55:48.328] Progress: resolved 0, reused 0, downloaded 4, added 0
[14:55:48.339] Packages: +408 -862
[14:55:48.340] +++++++++++++++++++++++++-------------------------------------------------------
[14:55:49.351] Progress: resolved 0, reused 0, downloaded 9, added 0
[14:55:50.356] Progress: resolved 0, reused 0, downloaded 17, added 0
[14:55:51.358] Progress: resolved 0, reused 0, downloaded 39, added 0
[14:55:52.359] Progress: resolved 0, reused 0, downloaded 54, added 0
[14:55:53.359] Progress: resolved 0, reused 0, downloaded 92, added 22
[14:55:54.359] Progress: resolved 0, reused 0, downloaded 124, added 46
[14:55:55.361] Progress: resolved 0, reused 0, downloaded 167, added 90
[14:55:56.360] Progress: resolved 0, reused 0, downloaded 228, added 171
[14:55:57.361] Progress: resolved 0, reused 0, downloaded 304, added 236
[14:55:58.361] Progress: resolved 0, reused 0, downloaded 375, added 309
[14:55:59.419] Progress: resolved 0, reused 0, downloaded 444, added 408
[14:55:59.428] Progress: resolved 0, reused 0, downloaded 444, added 408, done
[14:55:59.612] 
[14:55:59.614] Done in 14.5s
[14:56:03.404] 
[14:56:03.405] > @svelte-fui/core@1.0.0-alpha.14 storybook:build /vercel/path0/packages/core
[14:56:03.405] > svelte-kit sync && storybook build
[14:56:03.405] 
[14:56:06.597] If bundling, conditions should include development or production. If not bundling, conditions or NODE_ENV should include development or production. See https://www.npmjs.com/package/esm-env for tips on setting conditions in popular bundlers and runtimes.
[14:56:07.660] [1m@storybook/core v8.4.7
[14:56:07.660] [22m
[14:56:07.675] info => Cleaning outputDir: [36mstorybook-static[39m
[14:56:07.849] [33mThe CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.[39m
[14:56:07.862] info => Loading presets
[14:56:09.048] [38;2;241;97;97mSB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.
[14:56:09.049] 
[14:56:09.049] Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.
[14:56:09.049] 
[14:56:09.051] If you believe this is a bug, please open an issue on Github.
[14:56:09.051] 
[14:56:09.051] SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: /vercel/path0/node_modules/@storybook/addon-svelte-csf/dist/preset.js.
[14:56:09.051] 
[14:56:09.052] Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.
[14:56:09.052] 
[14:56:09.052] If you believe this is a bug, please open an issue on Github.
[14:56:09.052] 
[14:56:09.052] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/vercel/path0/node_modules/@storybook/addon-svelte-csf/dist/utils/identifier-utils' imported from /vercel/path0/node_modules/@storybook/addon-svelte-csf/dist/compiler/pre-transform/codemods/legacy-story.js
[14:56:09.053]     at finalizeResolution (node:internal/modules/esm/resolve:275:11)
[14:56:09.053]     at moduleResolve (node:internal/modules/esm/resolve:932:10)
[14:56:09.053]     at defaultResolve (node:internal/modules/esm/resolve:1056:11)
[14:56:09.053]     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
[14:56:09.053]     at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
[14:56:09.054]     at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:353:53)
[14:56:09.054]     at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
[14:56:09.054]     at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)
[14:56:09.054]     at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
[14:56:09.054]     at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)
[14:56:09.055] 
[14:56:09.055] More info: 
[14:56:09.055] 
[14:56:09.055]     at loadPreset (/vercel/path0/node_modules/@storybook/core/dist/common/index.cjs:16477:13)
[14:56:09.056] 
[14:56:09.056] More info: 
[14:56:09.056] [39m
[14:56:09.056]     at loadPreset (/vercel/path0/node_modules/@storybook/core/dist/common/index.cjs:16477:13)
[14:56:09.056]     at async Promise.all (index 2)
[14:56:09.057]     at async loadPresets (/vercel/path0/node_modules/@storybook/core/dist/common/index.cjs:16487:55)
[14:56:09.057]     at async getPresets (/vercel/path0/node_modules/@storybook/core/dist/common/index.cjs:16520:11)
[14:56:09.057]     at async buildStaticStandalone (/vercel/path0/node_modules/@storybook/core/dist/core-server/index.cjs:35384:11)
[14:56:09.057]     at async withTelemetry (/vercel/path0/node_modules/@storybook/core/dist/core-server/index.cjs:35757:12)
[14:56:09.058]     at async build (/vercel/path0/node_modules/@storybook/core/dist/cli/bin/index.cjs:2555:3)
[14:56:09.058]     at async s.<anonymous> (/vercel/path0/node_modules/@storybook/core/dist/cli/bin/index.cjs:2661:7)
[14:56:09.061] WARN   Failed to load preset: {"type":"presets","name":"/vercel/path0/node_modules/@storybook/addon-svelte-csf/dist/preset.js"} on level 1
[14:56:09.061] [38;2;241;97;97mError [ERR_MODULE_NOT_FOUND]: Cannot find module '/vercel/path0/node_modules/@storybook/addon-svelte-csf/dist/utils/identifier-utils' imported from /vercel/path0/node_modules/@storybook/addon-svelte-csf/dist/compiler/pre-transform/codemods/legacy-story.js[39m
[14:56:09.061]     at finalizeResolution (node:internal/modules/esm/resolve:275:11)
[14:56:09.062]     at moduleResolve (node:internal/modules/esm/resolve:932:10)
[14:56:09.062]     at defaultResolve (node:internal/modules/esm/resolve:1056:11)
[14:56:09.062]     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
[14:56:09.062]     at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
[14:56:09.063]     at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:353:53)
[14:56:09.063]     at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
[14:56:09.063]     at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)
[14:56:09.063]     at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
[14:56:09.063]     at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)
[14:56:09.093] 
[14:56:09.094] [35m[1mattention[22m[39m => Storybook now collects completely anonymous telemetry regarding usage.
[14:56:09.094] This information is used to shape Storybook's roadmap and prioritize features.
[14:56:09.094] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[14:56:09.094] [36mhttps://storybook.js.org/telemetry[39m
[14:56:09.095] 
[14:56:09.635]  ELIFECYCLE  Command failed with exit code 1.
[14:56:09.654] Error: Command "cd packages/core&& pnpm run storybook:build" exited with 1
[14:56:09.996] 
```

**Comment by JReinhold** [comment]
@ryu-man looking at this log output, I'd expect your Vercel environment is using Node 23:

```
Warning: Detected "engines": { "node": ">=20.x" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
```

I'd strongly suggest you pin that engines version in general, to not auto-upgrade to major versions. However if you can't/won't do that, you should try upgrading this addon's version to the most recent prerelease, along with Storybook core to 8.5.0-beta.5 which should hopefully fix Node 23 compatibility. Core storybook can be upgraded with:

```
npx storybook@next upgrade
```

**Comment by ryu-man** [comment]
@JReinhold I already set node version to both 20 and 22 (latest on Vercel) and none of them worked;  upgrading to the beta version of Storybook introduces errors reading .stories.svelte files

**Comment by ai** [comment]
@JReinhold using Storybook beta doesn’t help.

```
$ node -v
v22.12.0
```

```
Failed to load preset: {"type":"presets","name":"/workspaces/slowreader/node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.21_@storybook+svelte@8.5.0-beta.7_storybook@8.5.0-beta_lgz3ljqey7ytimvkenkvucorqq/node_modules/@storybook/addon-svelte-csf/dist/preset.js"} on level 1
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspaces/slowreader/node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.21_@storybook+svelte@8.5.0-beta.7_storybook@8.5.0-beta_lgz3ljqey7ytimvkenkvucorqq/node_modules/@storybook/addon-svelte-csf/dist/utils/identifier-utils' imported from /workspaces/slowreader/node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.21_@storybook+svelte@8.5.0-beta.7_storybook@8.5.0-beta_lgz3ljqey7ytimvkenkvucorqq/node_modules/@storybook/addon-svelte-csf/dist/compiler/pre-transform/codemods/legacy-story.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:353:53)
    at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)
    at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)
```

As you can see I am using Storybook `8.5.0-beta.7` and Svelte addon `5.0.0-next.21`.

I am just reporting it to help fixing the bug, seems like beta version need some other fix.

**Comment by lucas-subli** [comment]
Having the same issue:

```
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.21_@storybook+svelte@8.5.0-beta.8_storybook@8.5.0-beta_6xiag3w2y5gtaaaj3ena7zt24m/node_modules/@storybook/addon-svelte-csf/dist/preset.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error [ERR_MODULE_NOT_FOUND]: Cannot find module './node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.21_@storybook+svelte@8.5.0-beta.8_storybook@8.5.0-beta_6xiag3w2y5gtaaaj3ena7zt24m/node_modules/@storybook/addon-svelte-csf/dist/utils/identifier-utils' imported from ./node_modules/.pnpm/@storybook+addon-svelte-csf@5.0.0-next.21_@storybook+svelte@8.5.0-beta.8_storybook@8.5.0-beta_6xiag3w2y5gtaaaj3ena7zt24m/node_modules/@storybook/addon-svelte-csf/dist/compiler/pre-transform/codemods/legacy-story.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:353:53)
    at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)
    at new ModuleJobSync (node:internal/modules/esm/module_job:341:34)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:413:11)

More info: 

    at loadPreset (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/common/index.cjs:16512:13)

More info: 

    at loadPreset (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/common/index.cjs:16512:13)
    at async Promise.all (index 1)
    at async loadPresets (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/common/index.cjs:16522:55)
    at async getPresets (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/common/index.cjs:16555:11)
    at async buildDevStandalone (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/core-server/index.cjs:37138:11)
    at async withTelemetry (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/core-server/index.cjs:35750:12)
    at async dev (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/cli/bin/index.cjs:2591:3)
    at async s.<anonymous> (./node_modules/.pnpm/@storybook+core@8.5.0-beta.8_prettier@3.4.2/node_modules/@storybook/core/dist/cli/bin/index.cjs:2643:74)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

Node version: v22.12.0
Already tried with beta and non beta version of storybook

**Comment by SteveALee** [comment]
Same as @lucas-subli including node version

I did a vite install of svelte and then added storybook.

Tried bumping a few old dep version in package.json but no difference

Is there a work around?

**Comment by SteveALee** [comment]
Ah yes `NODE_OPTIONS="--no-experimental-require-module" npm run storybook` works! FTW

FWIIW I am using Git for Windows bash shell.

**Comment by JReinhold** [comment]
We're aware that this is a serious issue and will try to fix it ASAP ⏳

**Comment by JReinhold** [comment]
This should be fixed by https://github.com/storybookjs/addon-svelte-csf/pull/260 in [`v5.0.0-next.22`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v5.0.0-next.22) of the addon, let me know if the issue persists for any of you!

**Comment by SteveALee** [comment]
> This should be fixed by [#260](https://github.com/storybookjs/addon-svelte-csf/pull/260) in [`v5.0.0-next.22`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v5.0.0-next.22) of the addon

Pefect! Thank you.

**Comment by cbishop-fv** [comment]
> This should be fixed by [#260](https://github.com/storybookjs/addon-svelte-csf/pull/260) in [`v5.0.0-next.22`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v5.0.0-next.22) of the addon, let me know if the issue persists for any of you!

Thanks for this. This was also published as version 4.2.1--canary.31bd578.0. How long do your releases stay in Canary?

**Comment by JReinhold** [comment]
> Thanks for this. This was also published as version 4.2.1--canary.31bd578.0. How long do your releases stay in Canary? 

All PRs get an associated canary release to test it out. The version 4.2.1 is a bug in the release pipeline, it should really be 5.0.0 but because 5.0.0 is still a prerelease it bugs out.
We're not planning on merging this fix back to 4.2, if that's what you're asking?

I don't know if that answered your question.

**Comment by cbishop-fv** [comment]
> > Thanks for this. This was also published as version 4.2.1--canary.31bd578.0. How long do your releases stay in Canary?
> 
> All PRs get an associated canary release to test it out. The version 4.2.1 is a bug in the release pipeline, it should really be 5.0.0 but because 5.0.0 is still a prerelease it bugs out. We're not planning on merging this fix back to 4.2, if that's what you're asking?
> 
> I don't know if that answered your question.

I didn't want to go to 5 since its prerelease so yes I was hoping it would end up in a released 4.2.1 version that I could update to. I didn't expect it to be in 4.2 tho. I didn't know how long your canary / test cycles were and when I could potentially expect to update to 4.2.1. Thanks!

**Comment by ACERposS** [comment]
FYI this also occurs for me with `v5.0.0-next.21` and Nodejs `22.13.1`.
