### ISSUE TITLE
[Bug]: Internal server error: Cannot read properties of undefined (reading 'warningFilter')

### ISSUE THREAD

**Issue by lucasalska** [storybookjs/addon-svelte-csf#233]
### Describe the bug

Getting Internal Server Error when attempting to use the addon:
Internal server error: Cannot read properties of undefined (reading 'warningFilter')

### Steps to reproduce the behavior

1. Install addon-svelte-csf
2. Start storybook

### Expected behavior

That stortbook wouldn't crash

### Screenshots and/or logs

2:34:00 PM [vite] Internal server error: Cannot read properties of undefined (reading 'warningFilter')
  Plugin: storybook:addon-svelte-csf-plugin
  File: /Users/lucas/Web/boilerplate-agapi-svelte/packages/base/src/stories/product-card/product-card.stories.svelte
      at Module.compile (file:///Users/lucas/Web/boilerplate-agapi-svelte/node_modules/.pnpm/svelte@5.1.16/node_modules/svelte/src/compiler/index.js:24:37)
      at extractStories (/Users/lucas/Web/boilerplate-agapi-svelte/node_modules/.pnpm/@storybook+addon-svelte-csf@4.1.7_@storybook+svelte@8.4.4_storybook@8.4.4_prettier@3.3.3__sve_prueasknl5xxstsiclgrzmr4wm/node_modules/@storybook/addon-svelte-csf/dist/parser/extract-stories.js:56:21)
      at TransformPluginContext.transform (file:///Users/lucas/Web/boilerplate-agapi-svelte/node_modules/.pnpm/@storybook+addon-svelte-csf@4.1.7_@storybook+svelte@8.4.4_storybook@8.4.4_prettier@3.3.3__sve_prueasknl5xxstsiclgrzmr4wm/node_modules/@storybook/addon-svelte-csf/dist/plugins/vite-svelte-csf.js:25:25)
      at async PluginContainer.transform (file:///Users/lucas/Web/boilerplate-agapi-svelte/node_modules/.pnpm/vite@5.4.11_@types+node@20.16.10_lightningcss@1.27.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
      at async loadAndTransform (file:///Users/lucas/Web/boilerplate-agapi-svelte/node_modules/.pnpm/vite@5.4.11_@types+node@20.16.10_lightningcss@1.27.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:27)
      at async viteTransformMiddleware (file:///Users/lucas/Web/boilerplate-agapi-svelte/node_modules/.pnpm/vite@5.4.11_@types+node@20.16.10_lightningcss@1.27.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:61881:24)
### Environment

 - OS: Mac
 - Node.js version: 20
 - NPM version: pnpm 9.4.0

**Comment by xeho91** [comment]
Hi!

Thanks for reporting this issue. It seems that you're attempting to use svelte `v5`.
But you're not using `@storybook/addon-svelte-csf@next`, which supports it. From the error message, I see you're on version `4.1.7`.

**Comment by lucasalska** [comment]
Aaah, that makes a lot of sense! Thank you, I tried finding somewhere what I needed to do to resolve it, this is great! Thanks! I'll try it out!

**Comment by xeho91** [comment]
No problem. I'm going to close this issue. If you encountered another error that is similar to this one. Please do let us know. We will reopen and try to figure out what's wrong.

**Comment by lucasalska** [comment]
Can confirm that updating resolved the issue. A suggestion would be to make it easier to see in the documentation what is required for svelte 5 support, seeing as svelte 5 is in production now! :) 

Great work with the addon, this is such a quality of life enhancer!
