### ISSUE TITLE
[Bug]: Creating stories from Controls fails in Svelte CSF with `SyntaxError: Unexpected token, expected "}"`

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/addon-svelte-csf#240]
### Describe the bug

When viewing a story written in [Svelte CSF](https://github.com/storybookjs/addon-svelte-csf), editing controls and pressing "Save", the UI shows `did not save, unknown error`, and the terminal shows an error.

This is because [the editing logic of controls](https://storybook.js.org/docs/essentials/controls#creating-and-editing-stories-from-controls) doesn't support Svelte CSF, only regular CSF, which is a completely different format, language even. 

### Steps to reproduce the behavior

1. Create a svelte-vite sandbox, all stories there should now be in Svelte CSF
2. Open Storybook dev
3. Edit a control and press save

### Screenshots and/or logs

Error in terminal:

```
Error writing to .\src\stories\Button.stories.svelte:
SyntaxError: Unexpected token, expected "}" (8:9)
    at constructor (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:14251:15)
    at Wl.raise (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:16508:54)
    at Wl.unexpected (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:16525:18)
    at Wl.expect (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:16789:27)
    at Wl.jsxParseExpressionContainer (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:18853:75)
    at Wl.jsxParseElementAt (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:18894:122)       
    at Wl.jsxParseElement (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:18915:32)
    at Wl.parseExprAtom (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:18924:37)
    at Wl.parseExprSubscripts (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:21426:78)      
    at Wl.parseUpdate (.\node_modules\.pnpm\@storybook+core@8.4.6\node_modules\@storybook\core\dist\babel\index.cjs:21416:45)
```

### Additional context

At the moment it's not feasible to implement Svelte CSF support in Create from Controls. The feature works by modifying the AST, and given it's a completely different AST, the logic would have to be completely different. It might even be impossible at the current stage, given the only tool that allows you to _print_ a Svelte AST to source is [`svelte-ast-print`](https://github.com/xeho91/svelte-ast-print) which lacks features such as TypeScript support.

We should instead disable the feature from the addon. That is done by setting a specific parameter, and the addon can set that parameter for all stories it touches, so it wouldn't affect stories written in regular CSF:

https://storybook.js.org/docs/essentials/controls#disablesavefromui

_Originally reported at https://github.com/sveltejs/cli/issues/339_

**Comment by benmccann** [comment]
> the only tool that allows you to print a Svelte AST to source is [svelte-ast-print](https://github.com/xeho91/svelte-ast-print) which lacks features such as TypeScript support.

hopefully https://github.com/Rich-Harris/esrap/pull/13 will address that

**Comment by NeroBlackstone** [comment]
Same problem.

**Comment by nathancahill** [comment]
This affects the Storybook 7 to 8 migration tool as well.

**Comment by xeho91** [comment]
@nathancahill Can you please give us more context?

> This affects the Storybook 7 to 8 migration tool as well.

In this issue, we're talking about attempting to click "Save", after playing around with controls in the Storybook UI. I can't see a connection with Sthe torybook migration tool.

**Comment by JReinhold** [comment]
@nathancahill it's a pretty common error that can show up in a lot of different places, the two problems are not related.
