### ISSUE TITLE
[Bug] Cannot read property '$$' of undefined (can we please create a kitchen-sink dir?

### ISSUE THREAD

**Issue by frederikhors** [storybookjs/addon-svelte-csf#34]
### Describe the bug

I'm having a lot of issues event with this package.json:

```json
"devDependencies": {
    "@storybook/addon-actions": "6.2.9",
    "@storybook/addon-essentials": "6.2.9",
    "@storybook/addon-links": "6.2.9",
    "@storybook/addon-svelte-csf": "1.1.0",
    "@storybook/svelte": "6.2.9",
    "postcss": "8.3.6",
    "svelte-loader": "3.1.2",
    "svelte-preprocess": "4.7.4",
    "tailwindcss": "2.2.7",
    "tailwindcss-cli": "0.1.2"
}
```

with:

```
"svelte": "3.42.1",
"svelte-preprocess": "4.7.4",
"typescript": "4.3.5"
```

### Expected behavior

Can you please create a kitchen-sink dir instead of README snippet?

So we can see how to configure everything properly.

Please.

### Issues

```
Cannot read property '$$' of undefined
TypeError: Cannot read property '$$' of undefined
    at init (http://localhost:6006/vendors~main.iframe.bundle.js:1985:50)
    at new Button (http://localhost:6006/main.iframe.bundle.js:846:71)
    at Array.create_default_slot (http://localhost:6006/main.iframe.bundle.js:2000:11)
    at create_slot (http://localhost:6006/vendors~main.iframe.bundle.js:105060:29)
    at create_if_block (http://localhost:6006/vendors~main.iframe.bundle.js:11909:98)
    at create_fragment (http://localhost:6006/vendors~main.iframe.bundle.js:11947:38)
    at init (http://localhost:6006/vendors~main.iframe.bundle.js:106499:37)
    at new Template (http://localhost:6006/vendors~main.iframe.bundle.js:12023:71)
    at create_fragment (http://localhost:6006/main.iframe.bundle.js:2082:13)
    at init (http://localhost:6006/vendors~main.iframe.bundle.js:106499:37)
```

```
index.js:54 TypeError: Cannot read property '$$' of undefined
    at init (index.mjs:1779)
    at new Button (Button.svelte:854)
    at Array.create_default_slot (Button.stories.svelte:60)
    at create_slot (index.mjs:61)
    at create_if_block (Template.svelte:29)
    at create_fragment (Template.svelte:67)
    at init (index.mjs:1500)
    at new Template (Template.svelte:143)
    at create_fragment (Button.stories.svelte:142)
    at init (index.mjs:1500)
```

**Comment by frederikhors** [comment]
@shilman can you please help with this?

**Comment by j3rem1e** [comment]
Closing because of inactivity.
