### ISSUE TITLE
[Bug] Storybook build fails with webpack5

### ISSUE THREAD

**Issue by mrmikardo** [storybookjs/addon-svelte-csf#36]
### Describe the bug

I have recently upgraded from Webpack 4 -> Webpack 5, following the instructions here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5

Storybook stories now fail.

### Steps to reproduce the behavior

1. Upgrade Webpack 4 -> Webpack 5, change configurationg in `.storybook/main.js` to specify the "webpack5" builder.
2. Do `npm run storybook`.

### Expected behavior

Storybook to build successfully.

### Screenshots and/or logs

Screenshot of the error in question;

```
ModuleBuildError: Module build failed (from ./node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/svelte-stories-loader.js):
TypeError: Cannot read property 'replace' of null
    at extractId (/Users/jackie/directory/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/extract-id.js:20:24)
    at Object.enter (/Users/jackie/directory/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/extract-stories.js:98:43)
    at SyncWalker.visit (/Users/jackie/directory/node_modules/svelte/compiler.js:5654:17)
    at SyncWalker.visit (/Users/jackie/directory/node_modules/svelte/compiler.js:5684:19)
    at Object.walk (/Users/jackie/directory/node_modules/svelte/compiler.js:5742:19)
    at extractStories (/Users/jackie/directory/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/extract-stories.js:86:10)
    at Object.transformSvelteStories (/Users/jackie/directory/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/svelte-stories-loader.js:64:55)
    at processResult (/Users/jackie/directory/node_modules/webpack/lib/NormalModule.js:751:19)
    at /Users/jackie/directory/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/jackie/directory/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/jackie/directory/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at runSyncOrAsync (/Users/jackie/directory/node_modules/loader-runner/lib/LoaderRunner.js:156:3)
    at iterateNormalLoaders (/Users/jackie/directory/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at iterateNormalLoaders (/Users/jackie/directory/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /Users/jackie/directory/node_modules/loader-runner/lib/LoaderRunner.js:254:3
    at /Users/jackie/directory/node_modules/loader-runner/lib/LoaderRunner.js:140:6
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Environment

 - OS: macOS 11.2.3 "Big Sur"
 - Node.js version: v12.12.0
 - NPM version: 6.12.0
 - Browser (if applicable): N/A
 - Browser version (if applicable): N/A
 - Device (if applicable): N/A

### Additional context

My stories are a mixture of Svelte stories and JS stories. Using `storybook/svelte` `6.3.12` and `storybook/addon-svelte-csf` `1.1.0`.

**Comment by mrmikardo** [comment]
I think I found what the issue is here: I had a `<Story />` component which didn't specify a `name` attribute. When I corrected that, Storybook is successfully able to build again.
